import { type GenLayerChain, type GenLayerClient, type TransactionHash } from "genlayer-js/types";
import { address, alter, deployedSource, localSource, readFinal, record, requiredContract, runDeployment, sha256Ascii, type Stage, stableJson, txHash, uint, waitReceipt } from "../support/runtime.js";

const CONFIG = { prefix: "THESISSCORE", project: "ThesisScore", contractFile: "contracts/thesis_score.py", sourceSha256: "642C4672AA8E8A29674C50BE03822131B0CF03517EB3C05FB86332DE52DF7046" } as const;
const THESIS_SCHEMA = "thesisscore/thesis/v1"; const AUDIT_SCHEMA = "thesisscore/audit/v1"; const FINGERPRINT_SCHEMA = "thesisscore/fingerprint/v1";
const TITLE = "Three-clause macroeconomic forecast for the registered evidence window.";
const POLICY = "A clause is satisfied only when the registered evidence explicitly meets its stated threshold by the deadline. Otherwise it is failed, or indeterminate when the supplied evidence cannot safely decide it.";
const CLAUSES = [{ clause_id: "INFLATION", prediction: "Headline inflation will be below three percent by the deadline.", weight_bps: 4000 }, { clause_id: "JOBS", prediction: "The unemployment rate will remain below five percent at the deadline.", weight_bps: 2500 }, { clause_id: "RATE-CUT", prediction: "The central bank will announce at least one policy rate cut by the deadline.", weight_bps: 3500 }] as const;
const EVIDENCE = "At the registered deadline the official release reports headline inflation 2.8 percent and unemployment 5.4 percent. The official decision record reports a policy rate cut before the deadline.";

function fingerprint(policy: number, creator: string, key: string, deadline: number): string { const normalized = address(creator, "creator"); return sha256Ascii({ schema: FINGERPRINT_SCHEMA, policy_version: policy, thesis_id: `${normalized}:${key}`, creator: normalized, thesis_key: key, title: TITLE, deadline_unix: deadline, scoring_policy: POLICY, clauses: CLAUSES, evidence_text: EVIDENCE }); }
async function verifyPolicy(client: GenLayerClient<GenLayerChain>, target: `0x${string}`, policy: number, signer: string): Promise<void> { const value = record(await readFinal(client, target, "get_policy"), "policy"); if (address(value.owner, "owner") !== address(signer, "signer") || uint(value.policy_version, "policy") !== policy || value.purpose !== "BOUNDED_WEIGHTED_FORECAST_SCORING" || value.thesis_schema !== THESIS_SCHEMA || value.audit_schema !== AUDIT_SCHEMA || value.fingerprint_schema !== FINGERPRINT_SCHEMA || uint(value.minimum_clauses, "minimum") !== 2 || uint(value.maximum_clauses, "maximum") !== 8 || uint(value.total_weight_bps, "weight") !== 10000 || value.registration_before_deadline_required !== true || value.scoring_after_deadline_required !== true || value.score_derived_deterministically !== true || value.external_evidence_authenticity_verified !== false) throw new Error("policy read-back failed"); }
async function waitPast(deadline: number): Promise<void> { const milliseconds = Math.max(0, (deadline + 1) * 1000 - Date.now()); if (milliseconds > 180_000) throw new Error("deadline wait exceeded guarded limit"); if (milliseconds > 0) { console.log(`Waiting ${milliseconds} ms for the registered scoring deadline.`); await new Promise((resolve) => setTimeout(resolve, milliseconds)); } }

async function smoke(client: GenLayerClient<GenLayerChain>, stage: Stage, policy: number, retries: number, interval: number) {
  const target = requiredContract(CONFIG.prefix); const signer = address(client.account?.address, "signer"); localSource(CONFIG); const sourceHash = await deployedSource(client, target, CONFIG.sourceSha256); await verifyPolicy(client, target, policy, signer);
  const key = stage === "studionet" ? "STUDIO-MACRO-THESIS-20260812" : "BRADBURY-MACRO-THESIS-20260812"; const thesisId = `${signer}:${key}`; const resume = process.env.THESISSCORE_SMOKE_RESUME === "1";
  if (resume && stage !== "bradbury") throw new Error("smoke resume is restricted to Bradbury recovery");
  let deadline: number; let registration: TransactionHash | undefined;
  if (!resume) { deadline = Math.floor(Date.now() / 1000) + 90; registration = txHash(await client.writeContract({ address: target, functionName: "register_thesis", args: [key, TITLE, deadline, POLICY, JSON.stringify(CLAUSES), EVIDENCE], value: 0n })); console.log(`Smoke registration transaction: ${registration}`); console.log(`Smoke deadline Unix: ${deadline}`); await waitReceipt(client, registration, "FINALIZED", retries, interval); }
  else { const resumed = record(await readFinal(client, target, "get_thesis", [thesisId]), "resumed thesis"); deadline = uint(resumed.deadline_unix, "resumed deadline"); console.log("Smoke registration: RESUME_EXISTING_FINALIZED"); }
  const expected = fingerprint(policy, signer, key, deadline);
  const stored = record(await readFinal(client, target, "get_thesis", [thesisId]), "thesis"); if (stored.schema !== THESIS_SCHEMA || stored.thesis_id !== thesisId || stored.thesis_fingerprint !== expected || uint(stored.deadline_unix, "deadline") !== deadline || stableJson(stored.clauses) !== stableJson(CLAUSES) || address(stored.creator, "creator") !== signer) throw new Error("registration read-back failed");
  await waitPast(deadline); let auditHash: TransactionHash | undefined; if (await readFinal(client, target, "is_scored", [thesisId]) !== true) { auditHash = txHash(await client.writeContract({ address: target, functionName: "score_thesis", args: [thesisId], value: 0n })); console.log(`Smoke audit transaction: ${auditHash}`); await waitReceipt(client, auditHash, "FINALIZED", retries, interval); }
  const audit = record(await readFinal(client, target, "get_audit", [thesisId]), "audit"); const exact = await readFinal(client, target, "matches_complete_score", [thesisId, expected, 7500]); const changed = await readFinal(client, target, "matches_complete_score", [thesisId, alter(expected), 7500]);
  if (audit.schema !== AUDIT_SCHEMA || audit.thesis_fingerprint !== expected || audit.status !== "SCORED" || uint(audit.satisfied_mask, "satisfied") !== 5 || uint(audit.failed_mask, "failed") !== 2 || uint(audit.indeterminate_mask, "indeterminate") !== 0 || uint(audit.issue_mask, "issue") !== 0 || uint(audit.score_bps, "score") !== 7500 || stableJson(audit.satisfied_clause_ids) !== stableJson(["INFLATION", "RATE-CUT"]) || stableJson(audit.failed_clause_ids) !== stableJson(["JOBS"]) || stableJson(audit.issue_codes) !== "[]" || exact !== true || changed !== false) throw new Error("audit result failed exact checks");
  console.log(`Smoke ID: ${thesisId}`); console.log(`Smoke fingerprint: ${expected}`); console.log("Smoke score: 7500 bps; masks 5/2/0/0"); console.log("Exact gate: true; altered gate: false"); return { target, sourceHash, registration, auditHash, thesisId, fingerprint: expected, deadline, scoreBps: 7500, exact, changed };
}
export default async function main(client: GenLayerClient<GenLayerChain>) { return runDeployment(client, CONFIG, verifyPolicy, smoke); }
